### ISSUE TITLE
PolyUtils::powerToIndex(std::size_t, std::size_t, std::size_t)’ not a return-statement

### ISSUE THREAD

**Issue by c03n424** [rgl-epfl/learned-subsurface-scattering#2]
I have successfully 'scons' mitsuba 0.6, but when I  'scons'  the code of this paper,  there is a mistake as followed:

include/mitsuba/render/polynomials.h:110:5: error: body of constexpr function ‘static constexpr std::size_t mitsuba::PolyUtils::powerToIndex(std::size_t, std::size_t, std::size_t)’ not a return-statement
     }

How to solve this problem?

**Comment by dvicini** [comment]
Hi,
What compiler are you using? The `constexpr` keyword requires a fairly modern compiler. I think i was using GCC 8 or 9 when working on this project. And I also built it successfully using Clang on MacOS
Delio

**Comment by c03n424** [comment]
great,  it will solve this issue after I upgrade my gcc version, and it also need [https://github.com/AcademySoftwareFoundation/openexr/issues/235] to solve the compatibility OpenEXR with C++17 .

**Comment by c03n424** [comment]
By the way,  how long does it take when you generated one folder of you training data, such  '0000_ScatterData'. I seem to get stuck hen generating data.
