### ISSUE TITLE
Question about how to interpret exit point distribution as BSSRDF

### ISSUE THREAD

**Issue by spock-the-wizard** [rgl-epfl/learned-subsurface-scattering#5]
Hello, thanks for the great work. This isn’t really an implementation related issue, but I had a question about the particle tracer implementation ( `src/librender/sss_particle_tracer.cpp` ) used to generate the training data.

Specifically, I am looking into how to explicitly model the BSSRDF, possibly for various shapes.

I’ve noticed that empirical BSSRDF works, like the one by Burley in 2015, obtain radial profiles by simulating photons and interpreting the surface deposit of photons as the radial profile. It appears your code performs a similar process.

**My question is, how we can convert the exit point and throughput distribution obtained by your simulation to the BSSRDF.**

Additionally, Mitsuba offers emitter implementations such as spotlights and directional area lights. Can searchlight images rendered with these emitters be used to obtain the BSSRDF?

**Comment by dvicini** [comment]
Hi there,

These are interesting questions. At this point,  I would not build on this old code base anymore. I would suggest that you look into performing the simulations you need using Mitsuba 3 (https://mitsuba.readthedocs.io/en/latest/). It should be possible to implement everything you need using that framework, even directly in Python.

Best,
Delio
